## E-commerce Website Performance Analysis

You are an analyst working for a thriving e-commerce company called "Tech Haven." Tech Haven sells a wide range of technology products online, including
smartphones, laptops, accessories, and more. The company operates its online store and is keen on understanding its monthly performance to make informed
decisions.

***Data Description***

- **Visitors:** The number of visitors to the Tech Haven website each month. This metric represents the traffic the website receives.
- **Revenue:** The monthly revenue generated from the sales of products on the website, measured in thousands of dollars. It includes revenue from product sales
and any additional services offered.
- Expenses: Monthly operating expenses incurred by Tech Haven, including marketing, server costs, employee salaries, and other business-related costs. Also
measured in thousands of dollars.

***Business Tasks:***

1. **Conversion Rate Analysis**: Tech Haven is interested in understanding how well it is converting website visitors into paying customers. The conversion rate, which is calculated as the ratio of revenue to the number of visitors, is a crucial metric for this analysis.
2. **Growth Analysis**: The company wants to assess its month-over-month and cumulative growth in terms of website visitors and revenue. Positive growth is an
indicator of a healthy business.
3. **Profit Calculation**: Tech Haven wants to calculate its monthly profit, which is the difference between revenue and expenses. Understanding profitability is
essential for financial planning.
4. **High-Performance Months**: The company is looking to identify months with high conversion rates, profits, and net profits. These months could provide insights
into what contributes to success.
5. **Average Profit Analysis**: Tech Haven wants to know the average monthly profit over the year to get a sense of the consistent performance.
6. **Correlation Analysis**: The correlation between website visitors and revenue is of interest to assess whether there's a relationship between traffic and sales.
7. **Tax and Net Profit Analysis**: The company wants to factor in tax expenses and calculate the net profit for each month, which provides a more accurate picture
of profitability.
8. **Moving Average Analysis**: Understanding trends in revenue is crucial. Calculating a 3-month moving average helps in smoothing out fluctuations and
identifying trends.

***Key Business Decisions:***

1. Understanding which months had the highest conversion rates can help in optimizing marketing efforts during similar periods.
2. Identifying months with high profits and net profits can guide resource allocation and investment decisions.
3. Analyzing correlations can help in predicting future revenue based on website traffic.
Monitoring growth rates helps in setting realistic business goals.
4. Tracking moving averages can provide insights into long-term performance trends.


In [ ]:
import numpy as np
import pandas as pd

# Monthly data for the e-commerce website
visitors = np.array([1000, 1200, 1100, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100])
revenue = np.array([20000, 22000, 21000, 23000, 24000, 25000, 26000, 27000, 28000, 29000, 30000, 31000])
expenses = np.array([15000, 16000, 15500, 16500, 17000, 17500, 18000, 18500, 19000, 19500, 20000, 20500])

### 1. Conversion Rate Analysis: 

Tech Haven is interested in understanding how well it is converting website visitors into paying customers. The conversion rate, which is calculated as the ratio of revenue to the number of visitors, is a crucial metric for this analysis.

In [ ]:
df = pd.DataFrame({
    'month': range(1,13),
    'visitor':visitors,
    'revenue': revenue,
    'expenses': expenses
})

df


month  visitor  revenue  expenses
0       1     1000    20000     15000
1       2     1200    22000     16000
2       3     1100    21000     15500
3       4     1300    23000     16500
4       5     1400    24000     17000
5       6     1500    25000     17500
6       7     1600    26000     18000
7       8     1700    27000     18500
8       9     1800    28000     19000
9      10     1900    29000     19500
10     11     2000    30000     20000
11     12     2100    31000     20500

In [ ]:
cr = df['revenue'] / df['visitor']
cr

0     20.000000
1     18.333333
2     19.090909
3     17.692308
4     17.142857
5     16.666667
6     16.250000
7     15.882353
8     15.555556
9     15.263158
10    15.000000
11    14.761905
dtype: float64

### 2. Growth Analysis: 

The company wants to assess its month-over-month and cumulative growth in terms of website visitors and revenue. Positive growth is an
indicator of a healthy business.

In [ ]:
monthlyGrowth = (visitors[1:] - visitors[:-1]) / visitors[:-1]
cumulativeGrowth = (visitors - visitors[0]) / visitors[0]

print(monthlyGrowth)
print(np.mean(monthlyGrowth))
print("")
print(cumulativeGrowth)

[ 0.2        -0.08333333  0.18181818  0.07692308  0.07142857  0.06666667
  0.0625      0.05882353  0.05555556  0.05263158  0.05      ]
0.07209216612889566

[0.  0.2 0.1 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1]


In [ ]:
monthlyGrowth = (revenue[1:] - revenue[:-1]) / revenue[:-1]
cumulativeGrowth = (revenue - revenue[0]) / revenue[0]

print(monthlyGrowth)
print(np.mean(monthlyGrowth))
print("")
print(cumulativeGrowth)

[ 0.1        -0.04545455  0.0952381   0.04347826  0.04166667  0.04
  0.03846154  0.03703704  0.03571429  0.03448276  0.03333333]
0.04126885731696962

[0.   0.1  0.05 0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55]


### 3. Profit Calculation: 

Tech Haven wants to calculate its monthly profit, which is the difference between revenue and expenses. Understanding profitability is
essential for financial planning.

In [ ]:
profit = revenue - expenses

monthlyGrowth = (profit[1:] - profit[:-1]) / profit[:-1]
cumulativeGrowth = (profit - profit[0]) / profit[0]

print(monthlyGrowth)
print(np.mean(monthlyGrowth))
print("")
print(cumulativeGrowth)

[ 0.2        -0.08333333  0.18181818  0.07692308  0.07142857  0.06666667
  0.0625      0.05882353  0.05555556  0.05263158  0.05      ]
0.07209216612889566

[0.  0.2 0.1 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1]


### 4. High-Performance Months: 

The company is looking to identify months with high conversion rates, profits, and net profits. These months could provide insights
into what contributes to success.

In [ ]:
cr = revenue / visitors
net_profit = profit * (1 - 0.005)

print(np.argmax(cr) + 1)
print(np.argmax(profit) + 1)
print(np.argmax(net_profit) + 1)

1
12
12


In [ ]:
np.where(cr > np.mean(cr))

(array([0, 1, 2, 3, 4]),)

In [ ]:
np.where(profit > np.mean(profit))

(array([ 6,  7,  8,  9, 10, 11]),)

### 5. Average Profit Analysis: 

Tech Haven wants to know the average monthly profit over the year to get a sense of the consistent performance.

In [ ]:
profit

array([ 5000,  6000,  5500,  6500,  7000,  7500,  8000,  8500,  9000,
        9500, 10000, 10500])

### 6. Correlation Analysis: 

The correlation between website visitors and revenue is of interest to assess whether there's a relationship between traffic and sales.

In [ ]:
np.corrcoef(visitors,revenue)

array([[1., 1.],
       [1., 1.]])

### 7. Tax and Net Profit Analysis: 

The company wants to factor in tax expenses and calculate the net profit for each month, which provides a more accurate picture

In [ ]:
net_profit = profit * (1 - 0.005)
net_profit

array([ 4975. ,  5970. ,  5472.5,  6467.5,  6965. ,  7462.5,  7960. ,
        8457.5,  8955. ,  9452.5,  9950. , 10447.5])

### 8. Moving Average Analysis: 

Understanding trends in revenue is crucial. Calculating a 3-month moving average helps in smoothing out fluctuations and
identifying trends.

In [ ]:
window_size = 3
moving_average = []

for i in range(len(revenue) - window_size + 1):
    window = revenue[i:i+window_size]
    average = np.sum(window) / window_size
    moving_average.append(average)

moving_average = np.array(moving_average)
moving_average

array([21000.        , 22000.        , 22666.66666667, 24000.        ,
       25000.        , 26000.        , 27000.        , 28000.        ,
       29000.        , 30000.        ])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=81a512fb-7f43-4a50-bb50-e5cade97e6ca' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>